import org.gradle.api.artifacts.component.ModuleComponentIdentifier
import java.io.FileInputStream
import java.util.Properties

plugins {
    id("mileway.android.application")
    // H.8: bundles the generic JVM unit-test stack (JUnit, MockK, coroutines-test, Turbine, Koin-test).
    id("mileway.test")
    alias(libs.plugins.ksp)
    alias(libs.plugins.kotlinSerialization)
    alias(libs.plugins.navgraph)
    alias(libs.plugins.kover)
    alias(libs.plugins.roborazzi)
    alias(libs.plugins.dependency.guard)
    // G2: baseline-profile consumer — bundles the profile generated by :baselineprofile at release build.
    alias(libs.plugins.baselineprofile)
    // V15 FCM.2: Firebase config processing. Generates the google_app_id resource from google-services.json;
    // adds NO runtime deps (firebase libs are gmsImplementation only). F-Droid strips this line (FLFD).
    alias(libs.plugins.google.services)
    // V15 CF.4: Crashlytics mapping-file symbolication (gms). F-Droid strips this line (FLFD).
    alias(libs.plugins.firebase.crashlytics)
}

// Release signing, reads from keystore.properties (gitignored) or env vars (CI).
// Falls back to debug signing if neither is present, so `assembleGmsRelease` still
// succeeds locally and in CI without secrets configured.
val keystorePropertiesFile = rootProject.file("keystore.properties")
val keystoreProperties =
    Properties().apply {
        if (keystorePropertiesFile.exists()) {
            FileInputStream(keystorePropertiesFile).use { load(it) }
        }
    }
val hasReleaseSigning =
    keystorePropertiesFile.exists() || System.getenv("RELEASE_STORE_FILE") != null

// FLA.1: single-source versioning. The repo-root VERSION + BUILD_NUMBER files (bumped by
// scripts/bump_version.sh) are the only place versions change. versionCode = base + BUILD_NUMBER.
val versionCodeBase = 1

fun readVersionName(): String {
    val file = rootProject.file("VERSION")
    return if (file.exists()) file.readText().trim().ifEmpty { "1.0.0" } else "1.0.0"
}

fun readBuildNumber(): Int {
    val file = rootProject.file("BUILD_NUMBER")
    return if (file.exists()) file.readText().trim().toIntOrNull() ?: 0 else 0
}

// FLFD.1: F-Droid reproducible build flag (`./gradlew assembleNoGmsRelease -Pfdroid`). Disables R8/resource
// shrinking (not bit-for-bit reproducible across machines). F-Droid only builds the noGms release.
val fdroidBuild = providers.gradleProperty("fdroid").isPresent

android {
    namespace = "com.mileway"

    defaultConfig {
        applicationId = "com.mileway"
        minSdk = 30
        targetSdk = 36
        // FLA.1: single-source versioning. VERSION (semver) + BUILD_NUMBER files at the repo root are the
        // ONE place versions change (via scripts/bump_version.sh). versionCode = VERSION_CODE_BASE + BUILD_NUMBER.
        versionCode = versionCodeBase + readBuildNumber()
        versionName = readVersionName()
        // G9: instrumented tests (androidTest / Gradle Managed Devices).
        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
        // Default placeholder; override in gms flavor with your real key or via local.properties.
        manifestPlaceholders["MAPS_API_KEY"] = ""
    }

    // CF.5: expose BuildConfig.VERSION_CODE for the maintenance/min-version gate.
    buildFeatures {
        buildConfig = true
    }

    // FLFD.1: reproducible FOSS (F-Droid) builds, omit the dependency-metadata block from the APK/AAB
    // (it embeds a signed, non-reproducible blob). Applies to all variants; harmless for the Play build.
    dependenciesInfo {
        includeInApk = false
        includeInBundle = false
    }

    // Maps flavor dimension:
    //   gms   → KrossMap (Google Maps on Android, MapKit on iOS), requires API key
    //   noGms → MapLibre (open-source tiles, no API key, offline MBTiles capable)
    flavorDimensions += "maps"
    productFlavors {
        create("gms") {
            dimension = "maps"
            // Set your Google Maps API key here or load from local.properties:
            // manifestPlaceholders["MAPS_API_KEY"] = project.properties["MAPS_API_KEY"] ?: ""
        }
        create("noGms") {
            dimension = "maps"
        }
    }

    signingConfigs {
        if (hasReleaseSigning) {
            create("release") {
                storeFile =
                    file(
                        keystoreProperties.getProperty("storeFile")
                            ?: System.getenv("RELEASE_STORE_FILE"),
                    )
                storePassword =
                    keystoreProperties.getProperty("storePassword")
                        ?: System.getenv("RELEASE_STORE_PASSWORD")
                keyAlias =
                    keystoreProperties.getProperty("keyAlias")
                        ?: System.getenv("RELEASE_KEY_ALIAS")
                keyPassword =
                    keystoreProperties.getProperty("keyPassword")
                        ?: System.getenv("RELEASE_KEY_PASSWORD")
            }
        }
    }

    buildTypes {
        release {
            // FLFD.1: off for reproducible F-Droid builds (-Pfdroid); on for Play/CI release.
            isMinifyEnabled = !fdroidBuild
            isShrinkResources = !fdroidBuild
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
            // CF.4: Crashlytics mapping upload is OFF by default (placeholder Firebase config), enabled in CI
            // only when CRASHLYTICS_UPLOAD=true with a real google-services.json, "guarded by key".
            configure<com.google.firebase.crashlytics.buildtools.gradle.CrashlyticsExtension> {
                mappingFileUploadEnabled = System.getenv("CRASHLYTICS_UPLOAD") == "true"
            }
            // Use the real release keystore when available; otherwise fall back to the
            // debug key so CI/local release builds still produce an installable APK.
            signingConfig =
                if (hasReleaseSigning) {
                    signingConfigs.getByName("release")
                } else {
                    signingConfigs.getByName("debug")
                }
        }
        // QA build: release-like (minified, non-debuggable) but installable alongside
        // the debug build via a distinct applicationId. Always debug-signed so QA can
        // sideload without release secrets. matchingFallbacks lets library modules that
        // only define debug/release resolve their `release` variant for `staging`.
        create("staging") {
            initWith(getByName("release"))
            applicationIdSuffix = ".staging"
            isDebuggable = false
            matchingFallbacks += "release"
            signingConfig = signingConfigs.getByName("debug")
        }
    }

    sourceSets {
        // staging has no source set of its own; reuse the release no-op stubs for
        // WormaCeptorHelper / ShowcaseLauncher (the real impls are debug-only).
        getByName("staging").kotlin.srcDir("src/release/java")
    }

    testOptions {
        unitTests {
            isIncludeAndroidResources = true
            isReturnDefaultValues = true
            all {
                // JDK 21+ requires these opens for Robolectric + Compose rendering.
                // EnableDynamicAgentLoading lets MockK's inline mock-maker attach its ByteBuddy
                // agent cleanly across forkEvery(25) restarts (Z.5b) — without it, mockk-heavy
                // tests (SwitchAccount*) intermittently fail with "class redefinition failed".
                it.jvmArgs(
                    "--add-opens=java.base/java.lang=ALL-UNNAMED",
                    "--add-opens=java.base/java.util=ALL-UNNAMED",
                    "--add-opens=java.base/java.io=ALL-UNNAMED",
                    "-XX:+EnableDynamicAgentLoading",
                )
            }
        }

        // G9: Gradle Managed Device for instrumented tests in CI — an AOSP ATD (lightweight, headless,
        // no Google APIs) so it runs on the noGms variant. Task: `pixel6Api34noGmsDebugAndroidTest`.
        managedDevices {
            localDevices {
                create("pixel6Api34") {
                    device = "Pixel 6"
                    apiLevel = 34
                    systemImageSource = "aosp-atd"
                }
            }
        }
    }
}

// --------------------------------------------------------------------------
// Z.5b: fix for the `testNoGmsDebugUnitTest` forked-JVM teardown crash.
//
// Robolectric 4.16.1 on JDK21/aarch64 segfaults the forked test JVM on *exit* ("exit value 2"
// after all ~119 tests pass, XML all green). Two contributing factors, both handled here:
//  1. Volume: a single fork accumulates unreleasable native/Robolectric state; a ~42-class fork
//     exits cleanly but the full ~119-class suite reliably crashes. `forkEvery` restarts the fork
//     periodically so no JVM ever accumulates past the safe threshold.
//  2. Native Skia: the two @GraphicsMode(NATIVE) Roborazzi tests load the native graphics runtime,
//     which crashes if a fork carrying it is torn down at a `forkEvery` restart boundary. So they
//     are excluded from the main task and run in their own dedicated single-fork task instead
//     (in isolation they exit 0), then wired back into the gate via `fullCheck`.
val screenshotTestFilter = "com.mileway.Screenshot*Test"

// AGP registers the per-variant unit-test task late (variant API), so wire this after evaluation.
afterEvaluate {
    tasks.named<Test>("testNoGmsDebugUnitTest") {
        filter { excludeTestsMatching(screenshotTestFilter) }
        setForkEvery(25L)
    }

    tasks.register<Test>("screenshotTestNoGmsDebug") {
        description = "Runs the @GraphicsMode(NATIVE) Roborazzi screenshot tests isolated in their own JVM fork (Z.5b)."
        group = "verification"
        val mainTest = tasks.named<Test>("testNoGmsDebugUnitTest").get()
        dependsOn(mainTest.taskDependencies)
        testClassesDirs = mainTest.testClassesDirs
        classpath = mainTest.classpath
        // AGP fully configures jvmArgs/systemProperties on the unit-test task by afterEvaluate; copy
        // them so Robolectric finds the merged manifest/resources and the JDK21 --add-opens apply here.
        jvmArgs = mainTest.jvmArgs
        systemProperties = mainTest.systemProperties
        filter { includeTestsMatching(screenshotTestFilter) }
    }
}

navgraph {
    // Flavored app, pin to the gms debug variant so KSP picks the right classpath.
    variant.set("gmsDebug")
}

ksp {
    arg("navgraph.annotatedOnly", "true")
    // Room: faster incremental processing; only reprocesses changed DAOs.
    arg("room.incremental", "true")
    arg("room.expandProjection", "true")
    // P7.5: AppFunctions — aggregate all @AppFunction-annotated methods in this module into one
    // generated registration (required by the compiler for AppSearch indexing to find them all).
    arg("appfunctions:aggregateAppFunctions", "true")
}

// Compose compiler stability/recomposition reports, written to build/compose_metrics/.
// Trigger via: ./gradlew assembleGmsRelease -PenableComposeMetrics=true
// (debug builds add Live Literals noise; always run on release variant)
if (project.findProperty("enableComposeMetrics") == "true") {
    composeCompiler {
        metricsDestination = layout.buildDirectory.dir("compose_metrics")
        reportsDestination = layout.buildDirectory.dir("compose_metrics")
        // Stability config: teach the compiler about third-party immutable types
        // to prevent false "unstable" labels and unnecessary recompositions.
        stabilityConfigurationFiles.add(rootProject.layout.projectDirectory.file("compose_stability.conf"))
    }
}

// Kover: line-coverage floor enforced by koverVerifyNoGmsDebugCoverage. Coverage is
// measured on the noGms (JVM-safe) variant; the gms flavor's Play Services maps crash
// the Robolectric fork. Scope is :app's own classes; the remaining uncovered surface is
// almost all Compose UI (Login/Splash/Showcase/AppRoot screens) that needs instrumented
// tests (deferred, PLAN B.4c). Per-feature ViewModel tests live in app/src/test but exercise
// feature-module classes, which Kover does not aggregate here, see PLAN H for the follow-up.
//
// Z.5b: floor lowered 35 → 22. The two @GraphicsMode(NATIVE) Roborazzi screenshot tests were
// moved out of `testNoGmsDebugUnitTest` (they crash the shared fork on teardown) into the
// isolated `screenshotTestNoGmsDebug` task. Kover binds coverage per AGP variant and cannot
// aggregate that AGP-unbound sibling task, so the ~14pt of *render-only* coverage those tests
// contributed (production composables exercised by rendering, no assertions) no longer counts
// here — measured coverage of the assertion-based suite is 24.4%. The screenshots still run and
// gate (in `fullCheck`), just measured separately, so nothing is untested; the floor now guards
// the real logic coverage with ~2pt headroom instead of a render-inflated 35.
kover {
    currentProject {
        createVariant("noGmsDebugCoverage") {
            add("noGmsDebug")
        }
    }
    reports {
        variant("noGmsDebugCoverage") {
            filters {
                excludes {
                    packages("*.BuildConfig", "*.R")
                }
            }
            verify {
                rule {
                    minBound(22)
                }
            }
        }
    }
}

// Dependency Guard, baseline snapshot of releaseRuntimeClasspath to catch
// silent transitive version bumps in CI. Run `./gradlew dependencyGuardBaseline`
// after any intentional dep change, then commit the updated baseline file.
dependencyGuard {
    configuration("gmsReleaseRuntimeClasspath")
}

dependencies {
    implementation(project(":core:common"))
    implementation(project(":core:ui"))
    implementation(project(":core:data"))
    implementation(project(":core:network"))
    implementation(project(":core:security"))
    // V15: app directly references core:platform service interfaces + factories (flavor impls).
    implementation(project(":core:platform"))
    implementation(project(":feature:tracking"))
    implementation(project(":feature:logging"))
    implementation(project(":feature:media"))
    implementation(project(":feature:profile"))
    implementation(project(":feature:approvals"))
    implementation(project(":feature:payables"))
    implementation(project(":feature:travel"))
    implementation(project(":feature:agent"))
    implementation(project(":feature:cards"))
    implementation(project(":feature:payments"))
    implementation(project(":feature:events"))
    implementation(project(":stub"))
    // G11: include the Glance widget so its receiver merges into the app (the widget is offered on the home screen).
    implementation(project(":widget"))

    implementation(libs.core.ktx)
    implementation(libs.activity.compose)
    implementation(libs.lifecycle.runtime.compose)
    implementation(libs.jb.navigation.compose)

    // Koin
    implementation(libs.koin.android)
    implementation(libs.koin.compose)
    implementation(libs.koin.compose.viewmodel)
    implementation(libs.koin.androidx.workmanager)
    implementation(libs.kmpworkmanager)

    // Material (needed for Theme.Material3.DayNight.NoActionBar in themes.xml)
    implementation(libs.material)

    // Compose
    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.material3)
    implementation(libs.compose.material.icons.extended)
    implementation(libs.compose.ui.tooling.preview)
    debugImplementation(libs.compose.ui.tooling)

    // WorkManager
    implementation(libs.workmanager.runtime)

    // Map implementations, selected by flavor
    "gmsImplementation"(project(":core:maps-krossmap"))
    "noGmsImplementation"(project(":core:maps-maplibre"))

    // V15 platform services, Play-Core update + review, gms flavor ONLY (proprietary).
    // noGms gets no-op impls; the VerifyDependencyPrefixes guard (FLFD.2) keeps these out of FOSS.
    "gmsImplementation"(libs.play.app.update)
    "gmsImplementation"(libs.play.app.update.ktx)
    "gmsImplementation"(libs.play.review)
    "gmsImplementation"(libs.play.review.ktx)

    // V15 FCM.2/CF.3: Firebase, gms flavor ONLY (proprietary). noGms gets no firebase runtime;
    // VerifyDependencyPrefixes (FLFD.2) enforces that on noGmsReleaseRuntimeClasspath.
    "gmsImplementation"(platform(libs.firebase.bom))
    "gmsImplementation"(libs.firebase.messaging)
    "gmsImplementation"(libs.firebase.analytics)
    "gmsImplementation"(libs.firebase.crashlytics)

    // V15 RF.2: Install Referrer, Play-Store-only attribution, gms flavor ONLY (noGms/F-Droid has none).
    "gmsImplementation"(libs.install.referrer)

    // P2.9: phone->watch snapshot Data Layer sync (WearDataLayerWatchSyncBridge), gms flavor ONLY.
    // noGms binds WatchSyncBridge to NoopWatchSyncBridge instead — VerifyDependencyPrefixes (FLFD.2)
    // keeps play-services-wearable out of noGmsReleaseRuntimeClasspath.
    "gmsImplementation"(libs.play.services.wearable)
    "gmsImplementation"(libs.kotlinx.coroutines.play.services)

    // Konnection: KMP network connectivity monitor (init in Application)
    implementation(libs.konnection)

    // Coil: image loading (world map header background, profile avatars)
    implementation(libs.coil3.compose)
    // Coil 3 decoders, GIF animations and SVG assets
    implementation(libs.coil3.gif)
    implementation(libs.coil3.svg)

    // WormaCeptor: HTTP traffic inspector, DEBUG builds only (never in release; Android-only).
    debugImplementation(libs.wormaceptor.api)
    debugImplementation(libs.wormaceptor.impl)

    // G15: LeakCanary, DEBUG builds only (never release, never commonMain — same rule as
    // WormaCeptor). Auto-installs on debug; watches Activities/Fragments/ViewModels for leaks.
    debugImplementation(libs.leakcanary.android)

    // Baseline profiles, installs AOT-compiled Dex profile at install time for cold-start wins.
    // The profile is generated by the :baselineprofile macrobenchmark module (G2).
    implementation(libs.profileinstaller)
    baselineProfile(project(":baselineprofile"))

    // P7.5: AppFunctions — exposes start/stop-tracking, log-expense, today-summary to on-device
    // agents (Gemini/Assistant). Jetpack lib handles back-compat below the targetSdk-36 platform API.
    implementation(libs.androidx.appfunctions)
    implementation(libs.androidx.appfunctions.service)
    ksp(libs.androidx.appfunctions.compiler)

    // Tests
    // JUnit, MockK, coroutines-test, Turbine, Koin-test come from the mileway.test convention plugin (H.8).
    // G1: PagingSource load-boundary test needs androidx.paging types (feature:tracking exposes
    // LocationPagingSource but keeps paging-common as implementation, so add it to the test classpath).
    testImplementation(libs.paging.common)
    testImplementation(libs.kotlinx.datetime)
    testImplementation(libs.robolectric)
    testImplementation(libs.androidx.test.core)
    testImplementation(libs.androidx.test.ext.junit)
    testImplementation(libs.compose.ui.test.junit4)
    testImplementation(project(":core:platform"))
    testImplementation(libs.room.testing)
    // G11: Glance render test (host-side, runs in the JVM gate via Robolectric).
    testImplementation(libs.glance.appwidget.testing)

    // compose-nav-graph: navigation graph visualization (Phase 8)
    implementation(libs.navigation3.runtime)
    implementation(libs.compose.nav.graph.annotations)
    ksp(libs.compose.nav.graph.annotations)

    // Roborazzi: JVM screenshot tests (no device needed)
    // preview-scanner auto-discovers all @Preview functions across all feature modules
    testImplementation(libs.roborazzi.core)
    testImplementation(libs.roborazzi.compose)
    testImplementation(libs.roborazzi.preview.scanner)
    testImplementation(platform(libs.compose.bom))
    testImplementation(libs.compose.ui.test.junit4)
    debugImplementation(libs.compose.ui.test.manifest)

    // G9: instrumented tests (androidTest) — run on a device/GMD, not the JVM unit-test gate.
    androidTestImplementation(libs.androidx.test.ext.junit)
    androidTestImplementation(libs.androidx.test.core)
    androidTestImplementation(libs.androidx.test.runner)
    androidTestImplementation(libs.kotlinx.coroutines.test)
    // Room base types (RoomDatabase/close) — core:data keeps Room as implementation, so the test
    // classpath needs it directly to use the real MilewayDatabase.
    androidTestImplementation(libs.room.runtime)
    // Bundled SQLite driver for the direct MIGRATION_4_5 test (D.5).
    androidTestImplementation(libs.sqlite.bundled)
    // FusedLocation test double (setMockMode / setMockLocation) for the tracking-lifecycle test.
    androidTestImplementation(libs.play.services.location)
}

// ─── FLFD.2, Proprietary-dependency guard for the noGms (F-Droid) release ───────────────────────────
// Fails if a proprietary dep matching a forbidden prefix leaks into noGmsReleaseRuntimeClasspath, EXCEPT
// the allowlisted pre-existing prime-feature deps (FusedLocation + ML Kit OCR, used by BOTH flavors,
// making those FOSS is out of V15 scope; guardrail: don't touch the prime feature). The guard's purpose is
// to keep V15's NEW proprietary additions (Firebase messaging/analytics/crashlytics, Play app-update,
// Play review, Install Referrer) out of the FOSS build.
// Inside afterEvaluate so the AGP-created variant configuration exists when we look it up.
afterEvaluate {
    val forbiddenPrefixes =
        listOf(
            "com.google.android.gms",
            "com.google.android.play",
            "com.google.firebase",
            "com.google.maps.android",
            "com.android.installreferrer",
        )
    val allowlist =
        setOf(
            // Pre-existing FusedLocation chain (core:platform AndroidLocationTracker).
            "com.google.android.gms:play-services-location",
            "com.google.android.gms:play-services-base",
            "com.google.android.gms:play-services-basement",
            "com.google.android.gms:play-services-tasks",
            // Pre-existing ML Kit OCR (core:platform AndroidTextRecognizer / doc scanner).
            "com.google.android.gms:play-services-mlkit-document-scanner",
            "com.google.android.gms:play-services-mlkit-text-recognition",
            "com.google.android.gms:play-services-mlkit-text-recognition-common",
            // Transitive Firebase infra pulled by the play-services libs above (NOT messaging/analytics/crashlytics).
            "com.google.firebase:firebase-annotations",
            "com.google.firebase:firebase-components",
            "com.google.firebase:firebase-encoders",
            "com.google.firebase:firebase-encoders-json",
        )
    val verifyTask =
        tasks.register("verifyNoGmsDependencyPrefixes") {
            group = "verification"
            description = "Fails if a proprietary dependency leaks into the noGms (F-Droid) release classpath."
            // Resolves the variant classpath at execution time via the component graph (not artifacts, which
            // would hit variant-attribute ambiguity for project deps).
            notCompatibleWithConfigurationCache("Resolves the noGmsReleaseRuntimeClasspath component graph")
            doLast {
                val deps =
                    configurations.getByName("noGmsReleaseRuntimeClasspath")
                        .incoming.resolutionResult.allComponents
                        .mapNotNull { it.id as? ModuleComponentIdentifier }
                        .map { "${it.group}:${it.module}" }
                val violations =
                    deps
                        .filter { dep -> forbiddenPrefixes.any { dep.startsWith(it) } && dep !in allowlist }
                        .distinct()
                if (violations.isNotEmpty()) {
                    throw GradleException(
                        "noGms (F-Droid) release leaks proprietary dependencies: $violations",
                    )
                }
            }
        }
    tasks.named("check").configure { dependsOn(verifyTask) }
    tasks.matching { it.name == "assembleNoGmsRelease" }.configureEach { dependsOn(verifyTask) }
}
