#!/usr/bin/env bash
# PLAN_V36 P8 — drafts a What's New catalog entry from this repo's own git log + docs media.
# Reads ONLY `git log`/`git diff` on this repo and files under docs/screenshots|docs/gifs — never
# touches anything reference-app-adjacent (see .ralph/leak-patterns.txt / no-reference-leak.sh).
#
# Usage: scripts/whatsnew-draft.sh <since-ref> [slug]
#   <since-ref>  a tag/commit/ref to diff from (e.g. a previous release tag, or HEAD~10).
#   [slug]       catalog entry id; defaults to draft-<since-ref sanitized>.
#
# Output: whatsnew-draft/<slug>/entry.kt.draft + whatsnew-draft/<slug>/media/*  (gitignored).
# Human step after running: polish the TODOs, move media into
# feature/whatsnew/src/commonMain/composeResources/files/whatsnew/<slug>/, paste the
# WhatsNewEntry block into WhatsNewCatalog.kt, then delete whatsnew-draft/.
set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
CATALOG="$REPO_ROOT/feature/whatsnew/src/commonMain/kotlin/com/mileway/feature/whatsnew/data/WhatsNewCatalog.kt"

if [ $# -lt 1 ]; then
  echo "usage: $(basename "$0") <since-ref> [slug]" >&2
  exit 1
fi

since_ref="$1"
default_slug="draft-$(echo "$since_ref" | tr -c 'a-zA-Z0-9' '-' | sed -E 's/-+/-/g; s/^-|-$//g')"
slug="${2:-$default_slug}"

cd "$REPO_ROOT"

# 1. feat:/fix: commit subjects since the ref (release-note source material).
subjects="$(git log "${since_ref}..HEAD" --pretty=%s | grep -E '^(feat|fix)(\([^)]*\))?:' || true)"
if [ -z "$subjects" ]; then
  echo "no feat:/fix: commits since $since_ref — nothing to draft." >&2
  exit 0
fi

# 2. candidate media changed since the ref.
media_files="$(git diff --name-only "${since_ref}..HEAD" -- docs/screenshots docs/gifs || true)"

# 3. next version = max existing catalog version + 1.
max_version="$(grep -oE 'version = [0-9]+' "$CATALOG" | grep -oE '[0-9]+' | sort -n | tail -1)"
next_version=$(( ${max_version:-0} + 1 ))

# 4. today's date as three unpadded ints (kotlinx LocalDate(y, m, d) shape). `10#` forces base-10
#    so e.g. "08" isn't parsed as an invalid octal literal.
today_year="$(date +%Y)"
today_month=$((10#$(date +%m)))
today_day=$((10#$(date +%d)))

out_dir="$REPO_ROOT/whatsnew-draft/$slug"
media_dir="$out_dir/media"
mkdir -p "$media_dir"

media_entries=""
todo_captions=""
index=0
if [ -n "$media_files" ]; then
  while IFS= read -r file; do
    [ -z "$file" ] && continue
    [ -f "$REPO_ROOT/$file" ] || continue
    index=$((index + 1))
    numbered="$(printf '%02d-%s' "$index" "$(basename "$file")")"
    cp "$REPO_ROOT/$file" "$media_dir/$numbered"
    media_entries="${media_entries}            WhatsNewMedia(
                path = \"files/whatsnew/${slug}/${numbered}\",
                caption = \"TODO: caption for ${numbered}\",
            ),
"
    todo_captions="${todo_captions}//   - ${numbered}
"
  done <<EOF
$media_files
EOF
fi

commit_bullets="$(echo "$subjects" | sed -E 's/^(feat|fix)(\([^)]*\))?: //')"

{
  echo "// PLAN_V36 P8 authoring draft — generated by scripts/whatsnew-draft.sh $since_ref"
  echo "// Commit subjects considered since $since_ref:"
  echo "$subjects" | sed 's|^|// |'
  echo "//"
  echo "// TODO before landing:"
  echo "//   1. Polish title/description below (currently a raw commit-subject skeleton) using:"
  echo "$commit_bullets" | sed 's|^|//        - |'
  echo "//   2. Cull media/ down to the 1-3 screenshots that best sell this release."
  if [ -n "$todo_captions" ]; then
    echo "//      Candidates copied in:"
    printf '%s' "$todo_captions"
  fi
  echo "//   3. Move the culled files into"
  echo "//      feature/whatsnew/src/commonMain/composeResources/files/whatsnew/${slug}/"
  echo "//   4. Paste the WhatsNewEntry block below into WhatsNewCatalog.kt's entries list."
  echo "//   5. Delete this whatsnew-draft/ directory."
  echo "WhatsNewEntry("
  echo "    id = \"${slug}\","
  echo "    version = ${next_version},"
  echo "    title = \"TODO: title\","
  echo "    description = \"TODO: description\","
  echo "    media ="
  echo "        listOf("
  printf '%s' "$media_entries"
  echo "        ),"
  echo "    releasedOn = LocalDate(${today_year}, ${today_month}, ${today_day}),"
  echo "    modules = listOf(\"TODO\"),"
  echo "),"
} > "$out_dir/entry.kt.draft"

echo "drafted $out_dir/entry.kt.draft (next version=$next_version, $index media candidate(s) copied)"
